### ISSUE TITLE
Option to support tnoremap

### ISSUE THREAD

**Issue by sassanh** [vim-jp/vim-vimlparser#23]
Thanks for writing this great extension.
As you know today many vim users are migrating to nvim, it'd be great if you could update it to support nvim too. I have a huge vimrc file (around 750 lines) the only issue I see is that vimlparser is not currently supporting nvim's `tnoremap` as mentioned here https://github.com/syngan/vim-vimlint/issues/95. Could you please add support for this token?

**Comment by RianFuro** [comment]
I implemented neovim support a while back actually in #19.
Since the neovim command set actually removes quite a few commands still existing in vim-space, enabling neovim support is a toggle rather than being built in (because it would conflict with the existing vim command set). 
You can enable neovim support by passing true as the 2nd parameter to vimlparser#test(input, ...); or use the --neovim command line parameter for the js/python command line tools.

**Comment by sassanh** [comment]
Thanks, yeah it works alright with `--neovim`

**Comment by sassanh** [comment]
@RianFuro I were able to test it by adding `--neovim` in line 11 of `node_modules/vimlint/lib/vimlint.js` (adding it to the arguments it calls the `.sh` file with) but `vimlint --neovim <somepath>` outputs this:
```
error: unknown option `--neovim'
```
Any idea about this?

**Comment by sassanh** [comment]
I guess the npm package is not related to this repo. Right?

**Comment by RianFuro** [comment]
@sassanh well, I guess both the vimlint and the node-vimlint projects are using this codebase here as a dependency to destruct vim code into an AST. Since neovim support should be already provided by this my pr (though it could certainly do better, like proposed in #22), it's on the respective projects using the vimlparser to utilize this.

I suppose we could talk about the activation mechanism for neovim support if it's not sufficient... but since @ynkdir seems awfully inactive the last months, I doubt anything will come from it.

**Comment by RianFuro** [comment]
Also, to answer your first question: Since you only outlined your attempt I can only guess, but since you want to use it via the executable, you'd also have to adapt their argument parser to make vimlint recognize the --neovim option and then correctly pass it over to the call to the vimlparser.

**Comment by sassanh** [comment]
@RianFuro thanks for info. vimlint (the npm package) uses `vimlint.sh` from `vim-vimlint` which uses `vim-vimlparser` internally. So I ended up changing line 1943 of `autoload/vimlint.vim` to
```
  let p = s:vlp.VimLParser.new(1)
```
I hope I can manage my time so that I can create a PR for it (not by above method ofc, as it's just a dirty hack.) We can consider using `has('nvim')` instead of passing an argument too.

**Comment by RianFuro** [comment]
For the native implementation that would do. The transpiled js and python scripts don't have that option though :/

**Comment by haya14busa** [comment]
I wonder can we add less strict mode which just focus on parsing Vim script and skip checking correctness of the script.

This problem is not only related with neovim-only commands, but also with newly added commands to Vim itself.

**Comment by nickspoons** [comment]
To add to what @haya14busa said, vim now also has `tmap`, `tnoremap` etc. and these are currently flagged as errors

**Comment by tyru** [comment]
maybe #67 fixed this?
